version: '3.8'

services:
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9444

  cliente-service:
    build: ./cliente-service
    ports:
      - "8086:8086"
    depends_on:
      - mongodb
      - jaeger
    environment:
      JAEGER_SERVICE_NAME: cliente-service
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831

  ropa-service:
    build: ./ropa-service
    ports:
      - "8085:8085"
    depends_on:
      - mongodb
      - jaeger
    environment:
      JAEGER_SERVICE_NAME: ropa-service
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831

  mongodb:
    image: mongo
    ports:
      - "28017:28017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db


volumes:
  mongodb_data:
